name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Установка зависимостей
      run: |
        pip install pyinstaller

    - name: Сборка EXE
      run: |
        pyinstaller --onefile --console --name "TetradSmerti" main.py

    - name: Загрузка артефакта
      uses: actions/upload-artifact@v4
      with:
        name: TetradSmerti
        path: dist/TetradSmerti.exe
